[project]
name = "mcp-semantic-scholar-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.12",
    "fastmcp>=0.4.0",
    "pydantic>=2.10.6",
    "uvicorn>=0.34.0",
]
